server:
  port: 8082


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-empresa-service
          uri: lb://ms-empresa-service
          predicates:
            - Path=/convenio/**, /empresa/**, /convocatoria/**
        - id: ms-practicante-service
          uri: lb://ms-practicante-service
          predicates:
            - Path=/carta_aceptacion/**, /carta_presentacion/**, /constancia/**, /informe_ppp/**, /inscripcion_convocatoria/**, /plan_ppp/**, /practicante/**

