server:
  port: 8082


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-coordinador-service
          uri: lb://ms-coordinador-service
          predicates:
            - Path=/convenio/**, /empresa/**, /convocatoria/**

        - id: ms-practicante-service
          uri: lb://ms-practicante-service
          predicates:
            - Path=/Carta_aceptacion/**, /carta_presentacion/**, /constancia/**, /informe_ppp/**, /inscripcion_convocatoria/**, /plan_ppp/**, /practicante/**

        - id: ms-consejo-service
          uri: lb://ms-consejo-service
          predicates:
            - Path=/consejo/**

        - id: ms-supervisor-service
          uri: lb://ms-supervisor-service
          predicates:
            - Path=/supervisor/**