server:
  port: 8082


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-empresa-service
          uri: lb://ms-empresa-service
          predicates:
            - Path=/convenio/**, /empresa/**, /convocatoria/**

