server:
  port: 8082


eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-coordinador-service
          uri: lb://ms-coordinador-service
          predicates:
            - Path=/convenio/**, /empresa/**, /convocatoria/**, /carta_presentacion/**, /coordinador/**, /induccion/**

        - id: ms-practicante-service
          uri: lb://ms-practicante-service
          predicates:
            - Path=/carta_aceptacion/**, /constancia/**, /inscripcion_convocatoria/**, /plan_ppp/**, /practicante/**

        - id: ms-consejo-service
          uri: lb://ms-consejo-service
          predicates:
            - Path=/informe/**, /revision/**

        - id: ms-supervisor-service
          uri: lb://ms-supervisor-service
          predicates:
            - Path=/supervisor/**, /evaluacion/**